=== ForYeonCheon/YeonCheon/Let's_Study!!/unoKim/study_XML/ch12/booklist_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="booklist" type="ctBooklist" />
	<xsd:complexType name="ctBooklist">
		<xsd:sequence>
			<xsd:element name="book" type="ctBook" minOccurs="0"
				maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ctBook">
		<xsd:sequence>
			<xsd:element name="title" type="xsd:string" />
			<xsd:element name="author" type="xsd:string"
				minOccurs="1" maxOccurs="unbounded" />
			<xsd:element name="publisher" type="xsd:string" />
			<xsd:element name="price" type="xsd:int" />
		</xsd:sequence>
		<xsd:attribute name="kind" type="xsd:string" />
	</xsd:complexType>
</xsd:schema>

=== ForYeonCheon/YeonCheon/Let's_Study!!/unoKim/study_XML/ch12/booklist_schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<booklist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="booklist_schema.xsd">
	<book kind="컴퓨터">
		<title>유니티와 함께하는 세상</title>
		<author>심완보</author>
		<publisher>지앤북</publisher>
		<price>15000</price>
	</book>
	<book kind="소설">
		<title>셜록 홈즈</title>
		<author>신경숙</author>
		<publisher>지앤북</publisher>
		<price>20000</price>
	</book>
	<book kind="컴퓨터">
		<title>리눅스의 이해</title>
		<author>남궁성</author>
		<publisher>한빛소프트</publisher>
		<price>32000</price>
	</book>
</booklist>
