=== ForYeonCheon/YeonCheon/target/classes/Uno/ReadXml/XmlFiles/server-dtd.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Server (charactor)*>

<!ELEMENT charactor (nickname, level, job, hp, equipment)>

<!ELEMENT nickname (#PCDATA)>
<!ELEMENT level (#PCDATA)>
<!ELEMENT job (#PCDATA)>
<!ELEMENT hp (#PCDATA)>
<!ELEMENT equipment (weapon, shield, armour)>

<!ELEMENT weapon (damage, type)>
<!ELEMENT damage (#PCDATA)>
<!ELEMENT type (#PCDATA)>

<!ELEMENT shield (defence, durability)>
<!ELEMENT armour (defence, durability)>

<!ELEMENT defence (#PCDATA)>
<!ELEMENT durability (#PCDATA)>

<!ATTLIST Server id CDATA #REQUIRED >
<!ATTLIST charactor id CDATA #REQUIRED >
<!ATTLIST hp max CDATA #REQUIRED >
<!ATTLIST shield max CDATA #REQUIRED >
<!ATTLIST armour max CDATA #REQUIRED >

=== ForYeonCheon/YeonCheon/target/classes/Uno/ReadXml/XmlFiles/A-server.xml
<?xml version="1.0"?>
<!DOCTYPE Server SYSTEM "server-dtd.dtd">
<Server id="Rouge-Camp">
	<charactor id="koria189">
		<nickname>비바체</nickname>
		<level>29</level>
		<job>팔라딘</job>
		<hp max="100">80</hp>
		<equipment>
			<weapon>
				<damage>60</damage>
				<type>근거리</type>
			</weapon>
			<shield max="100">
				<defence>20</defence>
				<durability>100</durability>
			</shield>
			<armour max="100">
				<defence>30</defence>
				<durability>100</durability>
			</armour>
		</equipment>
	</charactor>
	<charactor id="zhfldk014745">
		<nickname>제노코</nickname>
		<level>21</level>
		<job>바바리안</job>
		<hp max="100">90</hp>
		<equipment>
			<weapon>
				<damage>70</damage>
				<type>근거리</type>
			</weapon>
			<shield max="100">
				<defence>30</defence>
				<durability>100</durability>
			</shield>
			<armour max="100">
				<defence>40</defence>
				<durability>100</durability>
			</armour>
		</equipment>
	</charactor>
	<charactor id="uno123">
		<nickname>와이엠텍</nickname>
		<level>33</level>
		<job>아마존</job>
		<hp max="100">80</hp>
		<equipment>
			<weapon>
				<damage>40</damage>
				<type>원거리</type>
			</weapon>
			<shield max="100">
				<defence>20</defence>
				<durability>100</durability>
			</shield>
			<armour max="100">
				<defence>20</defence>
				<durability>100</durability>
			</armour>
		</equipment>
	</charactor>
</Server>
